# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api"
  to = "https://jobs.github.com/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "https://devjovs.netlify.app"